Pass options directly to SSH using -o/-ssh-option
ALSchwalm/transient pull request #130
Opened 2021-04-15 17:00 UTC by benfogle

Passing options to SSH enables a bunch of useful things:

- Port forwarding
- `scp` files from a running VM using ControlMaster
- Dynamically controlling port forwarding using ControlMaster
- Fine tuning timeout, keepalives, etc.

2021-04-16 19:00 UTC, ALSchwalm requested changes
Thanks for working on this! It's actually a feature that has been requested before, so definitely useful. Just a few minor things before I merge.

2021-04-16 19:00 UTC, ALSchwalm commented on test/features/ssh_command.feature
> +  Scenario: We can run ssh with custom options
I'd like to keep the senarios in the imperative voice, if possible. So `Run ssh with custom options` here.

2021-04-16 19:00 UTC, ALSchwalm commented on test/features/ssh_command.feature
> +      And extra argument "-ssh-option ControlMaster=yes"
It kind of seems like we're testing ssh itself with this. Is there an option that has a simpler effect on the connection we could use to verify that we are passing things as expected? Maybe `-o VisualHostKey=yes` would work? Then we just need to check for things in stdout as we do in other tests.

2021-04-16 19:00 UTC, ALSchwalm commented on test/features/steps/steps.py
> +    for _ in range(60):
I'd rather this timeout be parameterized. So `the file "{file_path}" appears within {seconds}`

2021-04-16 19:00 UTC, ALSchwalm commented on test/features/steps/steps.py
> +            ['/bin/bash'],
A bit paranoid, but I was recently bitten by assuming that `bash` is always available. It would probably be best to use `sh`, given that (I think) `set -e` is POSIX anyway.

2021-04-21 17:48 UTC, benfogle commented on test/features/ssh_command.feature
> +  Scenario: We can run ssh with custom options
done

2021-04-21 17:49 UTC, benfogle commented on test/features/ssh_command.feature
> +      And extra argument "-ssh-option ControlMaster=yes"
Any test of `-o` is a test of ssh itself, though I agree it's a good thing to reduce the number of moving parts. I removed the `scp`.

2021-04-21 17:50 UTC, benfogle commented on test/features/ssh_command.feature
> +      And extra argument "-ssh-option ControlMaster=yes"
I would also like to keep flag in, because this is the particular use case I am interested in.

2021-04-21 17:50 UTC, benfogle commented on test/features/steps/steps.py
> +    for _ in range(60):
done

2021-04-21 17:50 UTC, benfogle commented on test/features/steps/steps.py
> +            ['/bin/bash'],
moot now

2021-04-21 20:10 UTC, ALSchwalm commented
:+1: This looks good to me. Thanks for the fix! Merging

2021-04-21 20:10 UTC, merged